bot:
    token: ENC[AES256_GCM,data:S+c5XsThYzRxE6Uk7Fl9m5W9RL9UW/TM2ZEKvZaAiga3nvI9r/rXWrXSRiuupQ==,iv:GIrfiZfT5rdWeTAvbsdbWWS84F+QObWYszOHrmIeA9Y=,tag:R0RyX3xhcjzUyIbLEZgI3Q==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:iiyBRuM5+54fw3Nc5vivCqRakfDWLtu8VORfBkEnODfG/UssyLNfxYZs7js9zlw6qXBFuQPYam9vrQ5NXWs4ezOslxBpowPSjAvMOWjO5KU=,iv:FF1ucF0zUlZVixRpallC4Gqry+bN0QERP7Mc8Nnc+/w=,tag:LoSfwvzAmbZH8oxySA2lgQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5V0JweEtRNDdla3JwaDZU
            TWZFVWZ3UTRwRGcwSWd3eXBTZHNhT1RSNFVJCmZuL0hnME1MWEVIM3dHb0dZNDJJ
            R1hNQTNHN0NSSndaWmQ3UzRSN1pMRGsKLS0tIDVMT3FuVHpzN2xYM2xuTTZXbldU
            cXpTZ2VzNExVeHNzdUYyaHF3N0cyWFUK7kEV/v025M1qySoE2bDTUmPVkNdoeTyc
            7E2kufx7eJmI6y2Y5p1pXLiEr4mWYcF9GaaOUvq9YL2I2F24OAeCUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T11:09:57Z"
    mac: ENC[AES256_GCM,data:7wAueVM++/ALu6S4e5SlQzKTn7WTShroI8wGHE/fCcJf0cPF8T8pE6iX0NE43iCVokHFiTN+YIV8AAPwwwMNgxvIHqP99tUYMO/Hd6NKmcwKI0S61WRS7OTzqkckSLVm1YLNlN4TQULEI05ONJOXcM+j8boWBtr5oz6+ABk+Wbc=,iv:CEFTU5lx2Da0zqi9jW43xB0Vs7XWwqkSYxgdNV6kdJ4=,tag:t8xzGEMi6mmkKRsHIYpD/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
