bot:
    token: ENC[AES256_GCM,data:ukXmpzuPIOidi7/tZxUhFthd9O8LScdU0dseoEuV/B1IcJ3HssVIq/5UGgeing==,iv:lXMSmVVKzi1J89x2+9sOxP9DpepcWZCif/mn4cOF6rY=,tag:SUmZ5FqRyAgqom2D+S9qFg==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dEkzbFhkdFhOM1g0Vm12
            Tlh1R2QxR0Z1NGFIdEJQQWRtM0dzWXppSTEwCnNFNnozZVNOOGh0Q3psYUJBMy9o
            aXM2d3dBMXdCOFpTcG1RWmM2WUJad28KLS0tIEZnZUlMeEpYcW9JbldxSVZCWnhM
            MXRLcFkzd0FQWVhaeVNhSU16VTExc2cKylldUCFYVSBhJ4fbY7tKzezrFaJbrIcL
            bYDix5Sj+GhhwpnulMifR5MBmBjxAMrMLaEMf+WM1O00lPhSFKVifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:12:50Z"
    mac: ENC[AES256_GCM,data:uQ3IojOn7Jlc1FSSSroCfU2U1Zq9UJwpQL6G+63IFqyuD12T5E3mcN+fmAUTyVjL3bKLFl1W79p+MwRmO7jQ7d5d/QZEcdX7wv4HWbm6Nd/cnLO59zB2PKxVz3vmEqprcNpGIB6WUnt/enIvkuoCXD/D01fs4SNtgsdVZb1hd5A=,iv:sYHLviOhdBtxy2X95RrP0rCbj2i9cWqmFh3C2dt+wJY=,tag:p6H9WXXphcxG976MwBnKug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
