env:
    - name: ENC[AES256_GCM,data:mWyGo/t81lhe6Ts=,iv:DgQzHDfaQzho3hjfGW1qPVYAAEYPAPqlhPuIqeE6Urc=,tag:Xz6QpiPCkqYHYWhKfGxCSA==,type:str]
      value: ENC[AES256_GCM,data:gHZh,iv:2e3F+7zlQENTTfDk3RbFWyLGwLlQsPXj2xMuG0Hfgi8=,tag:qo5OmygzScZPa85hnTDdKg==,type:str]
    - name: ENC[AES256_GCM,data:pC9qR6CpSzY7MDY/wA==,iv:Dn9gVZIH7FdewYvneBlIHMitWMTt/C6yNIQw6vlM0aI=,tag:T4fE8BjwdCNEIGv8U22SdQ==,type:str]
      value: ENC[AES256_GCM,data:4Q/0,iv:8Aksevhcz9r9yC0TD2wAZoNyVO2uyl39NQcf9nmXyN8=,tag:WT46a3P/IsBktPwH80h0WA==,type:str]
    - name: ENC[AES256_GCM,data:5YelJ8ypIOBM+v/YUhksnXg=,iv:5nrIu1QYNM3w0dK7emtz5uH9oLesK8OgActFHOwyVNE=,tag:q3tt9rweh6BUAzkeXiFaqQ==,type:str]
      value: ENC[AES256_GCM,data:5ZBo,iv:FMgGYZwa2D8jOw5Bo4rXPqrSemwrcGk1hHmAWuxG/ds=,tag:0m9yynO9aQPMgev2hdr5EQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dzU2emlZMEhVL2hVS2lp
            dFRmT2l3ZVRPc3RRMkZ4WkJCNXZ5d0NRYmtRCjN1ZmVtUVFWbzZHSFgzTTVzdGNw
            d2Y2ZmovakoyWit2b1RwbU9uTFdubVEKLS0tIDRhd045c0JoVWZYYXpuZWZwM01M
            eDYvdWdDakYrTGwyV2QzT3VnN2J1dkkKn60PD7r3AtU8U3UZVrF10D060zMt60gV
            GVU/99RwiWrWvZg18lfknpVSCjtuVYMCrZ2qL71lNOj85hi857J5VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:09:41Z"
    mac: ENC[AES256_GCM,data:FX3C1x6NAvAbaKIMNAjqIyKOqRyEG8/hDdUUNAhd5Yqgu3u95bD6oIeJkUgFErRQlrrdPSVeYlqQMCcbXWu85FLGC5lHHh2xhAWxd0ElM1YWFJYH3WJ9IGzz1uOiypa1EmkAUxq/hlnhQJev8UG0dEyrXycA+REdaJzPcSUIEsE=,iv:ccJgyQhOwSJRlgQt1UZTdNML6peFwqZ/16mPvfWSuw4=,tag:Llhb4vBSnfDONIlA/R5UhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
