bot:
    token: ENC[AES256_GCM,data:mfS6+lBWAw40rX2S9AT5Cy6FrVpq4UN3MRYjQ9kdyO4GAxsQ69bYhOhGhEe+Uw==,iv:3o/Odlk1/CiuYvNgQzYXBSdBWLsUU0/hXkGG9Zereq4=,tag:qDqrYfS9cw/lHPHFnAZ7WA==,type:str]
    webhook_token: ENC[AES256_GCM,data:mJtDwNZGreEB9MtEWhJj,iv:iWdK0L4eT/L1krTrPOGhK73pr0G8XwVAFtbRF5BoOeA=,tag:IMOW+wBQeoY8eVJdwuTFPw==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:Pqk06LiknKbiA1jWHqbR+PWGFO3tp7Md1/3GR2jgg0/GnrjIBSzle4+UIE+/w9gsNpBWJiEqeJG+9r4G6eVzcQC0/DiEl24wRFU9SQMrx2lrlk8hcmQajOC5+rMLQ4EFUUKguPcz615TgPvp09O+PRP1AIALGyYlM0fyV9FUltDWTL4fuKp+HIs0p3RTKhJ8geGHE4+e9tGMdGJV50s86Rg+XVOdxvqhSJgA,iv:nbfmkMGdG6XMVeNDzhCDrMsy5dIhW9wSNqq/L7Ee/c0=,tag:2GjyLvIbc79/eAdMLjdxsg==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQjZQM0F4ZDNpdGkyWjJ3
            TnFOK1VDbC9rMklNRzMrN3RtZENnMktCMUNZCnhQdmxJZ0NMY1U5eFVzRzNiSThW
            T0F0VHZReDVnc2xKWXZ3S1dsNnloUVkKLS0tIHV5cHByTlpJM2Q1aWlpWkVNZWxh
            ZHVUOW9kbDRDSk9SUklzeVpsdmExbmsKO1h607r0e9cCxRqIhYPVWe06fQgtaDKu
            aZLT1ZNwp0+ObYYVNrZ1jsscLAjKyn/EEkXskRwZ1xrhkWtsRxAPyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:38:59Z"
    mac: ENC[AES256_GCM,data:LmF1KrCAvS/3k598tNXPYIUckDj48lBVKQ8mDBXIyyB54LRX6yV7oPLbXyT6PvilmkAZ7OIeA6pv43eRoZj829iO/7fDWR5rn4xbjQ/4CURSdzip05LGZCyTNyYXEnJ+ehd72VQ+D77AcFSyup0x+ijhhM+lZo/TGgn0pnXqh2U=,iv:fox2yhybOJbIPI/mEVpUF6hXaJrpERflQ8WFr7Qm1Qo=,tag:Kmi48kIPxEcuI5rGQMsqJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
