bot:
    token: ENC[AES256_GCM,data:BOee2pAxFs9nwiFz4odBhP8rLU1IABgLhcLLC+n3upwypsu136xARL3Df423/w==,iv:iF+mlk77feqFHlQTaYGKsxF61/b/ZQexypEyPBDtz/Y=,tag:RYh3eyIZ61Xov5r4A5xWtw==,type:str]
    webhook_token: ENC[AES256_GCM,data:e2IFoYVeybgJzp3DQAIg,iv:aVQ2+CKyIyadCR+mkFkJHz0xvsH6LaBkBpTxmh0v0ro=,tag:/ug1SPLA6FnltM58E5J+cw==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:F0pnjGXI51WMBpih7m6+qyHJRikzF3GGHo1yGTKyyA9qFeKT7HhbHnWDXwY5XfJZRMA0fbDVMNtWNv/Odg/z9OXrEupYhsOFgbXXbkTOkkVaiG9CDOfKLZKbxAqRdwFLDa4+RONe7ExIYWyJh11JS+H3VGWDE5DndTIZdGRk9kfslgYF7g4093QJYwbY3VFiuIUzAnChw++tz++axmKRzyeKESQKlmhZ1Zxs,iv:JrC44NSERIm21sGelSc+DigFvT5T9IzjZmEwYAGA8pk=,tag:C5ETqSEtnEEdnW50HVf9og==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbUx4Wm1UajQrcURxaGdm
            RmZQVnNIRysvTVowVm5ZM2xES2ZYOUhNS3pzCjcxT0tHT3NOY0Q2L1hiM3JnOXYz
            ek1yb3JwdlZEUFhIK1pobi9GOFdRRVkKLS0tIDFKbjVYUFNHM1M3U29sa1pxUGpz
            V0NPQU0zYURaRXRiTEN0ZEV1VFJVeXMKSXsJehBptkS45Qe1VLYZySYgYaXSAhzB
            XWrbK5XJGMUMi4Yr8bhsihctLvw36x03HOSmQYT/mRBSVe3J0B8j1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:25:56Z"
    mac: ENC[AES256_GCM,data:Yf5rMfFmgOKz6JjT6eZIu4kQa+GDv02WndMl0M8jqIJl2Ry/bj+7iewHfl/NpeTGJICS/QDjhxUEOrEscC0ejKNuKKwAE00avu1SuhdcRql0eatBh3+2lRRZv+rokYqyYLio0NMOU+I9GRiPI7MqhVVkp2KtRPU2TT/FMESSRpo=,iv:WMeppjifK9RRwbmgjloLN8YXX8/9DD2bemFQG6Xy5io=,tag:Qqnar2A/GAy59IAxVJ7GrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
