bot:
    token: ENC[AES256_GCM,data:4/1eDaXQTBdSm2Y0KArw7XvzGCwtRsiVRB+3mxIfzKOQWYZHPVwfAvcZj7wQpw==,iv:GoiUzO1mQcKY2J77aujDrgX1qbHWJPWE4X4YKMYvU4g=,tag:HqogSEmMQy75e6TwoXpaHA==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:7oXYD9bleZSMW332W1g5hA0Ua+dv9NjtnHCJ5MwLdns6LLKZDCLDlO68jNI7VK09+IeJSBbn7bHmLQbrX4eHvpUBGnjUi9KbMSa0YhMRmerQCIKVST/bTcqevinS/MzLZgSn8ZBx9kbYCrp7teqJWNGiQX0O/nUls2G08oi2LA8e2PG9Aos891qGjmZTsdr/4aitupVGMsVXU97REZ6QNTMrpp86mFRzAXNS,iv:Puru9tbigBlABDcK+/DiZM/J+kWh/d5PZj9YLW5SJAE=,tag:4C7KapTQfwMn0iiLYniejQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b1VhbEpzTElpWEh2UHZU
            S0NrQUdCOHE0ZVlQVlJQRWVjeUVQU29JZGdFCmcvTmhkQllGaE5YMy9TVWZPWWJ2
            UTFlNm5IZ3dKbEp2cjhMLzg3cDBiUHMKLS0tIG5WR2Y4WnlESGovRE5FMnQ1WDJm
            SW8xdCs5NDdseERTeTcwMytsWnllczQKCML2n0lClJztJDBZ2kW23/l0xlbFvQ0X
            5UglhjCdDr0EwbxDFR+Hu1aftESdD1vMXr2fuT9Sj1Ti1uckRwZMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:08:22Z"
    mac: ENC[AES256_GCM,data:x0z9Sn1dmovjQekUCFzIy6h8EMCQnLomuV21jazECLIXi5Zh9vNIQtoOOgvEtXWXBZfpKRyVm6B08ZZhBOsp1TytKq5GmcKb5mIWYbLluFZtkw/cqmfrBsAD75LkpU92D28xDfXxdZJSq1ZkWDFh/Sq7gVnx44xLkVdmJAxY3Ko=,iv:I8Rl3v6CO1IbgWmbcRtNLXjrFonvRlVwWNcMGFPAZe0=,tag:pqOtBVX4POwgscUWB1T7Rg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
