bot:
    token: ENC[AES256_GCM,data:YP8ZL761MbVOGz44iZ3DN0XkUh/mTZVHG9yUhpw6WHnH8mW1ih2ppNEL3FAqqw==,iv:jyryyeEkzLeyA297qg/mWkb3DrUnTvBIC2HxtqER+qY=,tag:DK9lwre9W+vnj0m6nFWmzg==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:/GddHEgzF+ieewUNiRhiCJHTuRd+h14c5z7IhjiGyUSUz/o4b9n2CbE2evosCXcwi2czZciNf27UxL3VrI0NFrfOogTsLwkROPScmqNYp8KRu7nnArYqdXsNGdpAJc0J3NuWrSp0jmTAen/mzOzQXO1OZCe4i8lCDReMu17Xq4mfC2Srn5vm5e3skiKQdthAvWP09V94Am/ijrnqqfvEK0AF5t3FRUZwAHY2,iv:wl4agMKSskPlFlr1RkfKnotTDF/dmMGcsbjyv7O0c+Y=,tag:trkTssX5se3vakHyRoTTEw==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMlZ1eUJHZjViSVN0OXhS
            Q3dGRDZNaUg1OVBVVHVqQkhpM3JqcWlnWlNJCmdnYk5QZHo1QjBnQU9VaE00cnds
            RmNtSGQxQWhhcDNCNzdBbTNrS1NCdXMKLS0tIHdaTitzRmE5cUtoUVIrbW0rWkxj
            c29VenBPQzJQRUxmOUZwUUJ0ZVBPcGcKRXXgbrWW+3RUDV93GyBwytefRiekqjyf
            BG6P6V5T2WRKr0inJi0vqYaJu+4WyrH0YDfMG2S6NjdecKZweeeTVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T19:51:27Z"
    mac: ENC[AES256_GCM,data:3AtGHyx5p1Hqjle+BZPv35Iwt/YNlJzkv3zq1FA8PKz68nsrrcKWpAVZcOuMTM8qCGmkgnNbyzo98JEHf7cgXgpiQjbQWmNhaw27wzePK9mGB0nKijCV25G8j3Z8DVL5My+48iP8pRfTwBmf3QfsXEt91RKY8KYskItRjouSefQ=,iv:Dgcm//1/emXcUKj+25p32h5jKoaCBBFTFdvCaFdTfAI=,tag:g0+Sqkg33o5k2s11hD9vuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
