log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "penalty-game-poller"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
matchmaking_worker:
  count: 2
  interval: 1s
  batch_size: 10
expired_shots_worker:
  count: 2
  interval: 5s
  batch_size: 100
  shot_expire_duration: 5m
leaderboard_recalculator_worker:
  count: 1
  interval: 1m
  batch_size: 1
