postgres:
    connStr: ENC[AES256_GCM,data:zSPRw0YpAAZJA7IwwWNnLTIk/5knm/AA59X9P0RzX5plJxhiTybWS5VZGEWFszO6SeClDQMilSKo7i82u2al6i3sigxreinEIuDOU9Oa1bk=,iv:kAi7mhWAyMskN8MjldxifK2DiNpwx69IO1JhL057GtI=,tag:Oma7I2kc66e6bMYEMqIcww==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySWpkRkUvSmEveHlFSUk1
            UXFoMFY5SVVaQjhFb2tFeHhsQ1Y0MU9YQ0FFClVCNmF2R0g2S0NuY0pCRG9FeUor
            TWdjRzNWeFN4NFlMWWlGU2pIZElDU1kKLS0tIFl2YmtQVTBoZ2F0L3NPc0c3cmV2
            QW45WUk3aVJsZUZzWlJvblFqNlpqL1UKZRhA2WO7ZN8qmUeLCRky/nBqo6M1Fue4
            +kpm0AoLuataKw3rKM8sO53DNbQJJO/1oX9q6w7Aj265tz5V/+xwyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:12:35Z"
    mac: ENC[AES256_GCM,data:s7CDs5hPx8PGNjs+oB3MXRLiSodgf6N+YcHs91SkEbCb9N6aDCKUmiyRHdvboC2HuvSN4AkK3WzWWzRrlGWJQvE6O8X3QBWmQEZsmeXecV75va2Hwl5fbXIDFcFrO0OhKMjFxNfjoqnGcOvFXcuuq3fRKwKCESC8iTdNFLntVdo=,iv:yts8Vlw2Pv4acCA52FWDSrmmJKA7hHG8Qc5M54gHseU=,tag:IaljaqUOdE3Xc+bnB188FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
