apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/redirectionbot-cm.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/app/redirectionbot"]
        args: ["-config", "/app/config/config-redirectionbot.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        {{- with .Values.ports }}
        ports:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-cm
