bot:
    token: ENC[AES256_GCM,data:LAoyMoNxP/kcb6n2diTIPK3ghMeG0pAto3pFV5uZLR2ArIf0V8HuTEn9hSAqoA==,iv:d2ILF3Iiu51daftTYb/FeFKG+2LkbbxfaxOgDEGE3nA=,tag:lRNdp5KfpxtC4Rx/6GdFXw==,type:str]
postgres:
    connStr: ENC[AES256_GCM,data:AG52+f0j3EMmyNwZRjNrR+vYFL/AlUZBwiitbQzpY+KQVgghtkpo/6+5typqSBCG3ow/KeKY6kGnXKMFeRX+sDoGtyrD+27A64f+iPxJLQ4=,iv:SDwSUp0xgKF7Kmqge6RHBaU4PqvvTScVDhGcY2EWPcA=,tag:Fa3GHqSiHrR2Hb2Q0NcvLQ==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VnIrNmNsOW9rdmIxMmJC
            dDIxUDVDOTN0bURhNldPWnQ4T05MYkpKRmxNCkVpNEpxN3BtejJFejNXM2Focm1J
            d1VRMjRwU2M0ZGVyV2VGZ3Y2Tlp4SVUKLS0tIGpWL3VCRDYyZEJaeDFQRHRsOFdu
            bXY1cGU4MnVoTWQ4ZnpWN0p3WHRscTAKp+/RcxGYbAwbxlMtRxUnsuk2iVi1sXaS
            GRVxhGLHpv4Vk0/VmmoXJyBwPI6Rv6XZxYVMoaujQ/aPnAlodseCSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T12:14:57Z"
    mac: ENC[AES256_GCM,data:w/JRomFMGmKA8SB8osaqnSedO8cEoqZVX+hlC8sN8sXq8eXgHpS6CWXKo/goIUb0p5c566X7ACr6IALubyabfdgGrnMnrdf3hrRh2qG1Rs5uSGamEA8x1QqEXDsAaLmF0JKWBJyUTJ0Ig8kqqBB0YS81rIstKfRzxZ6kDptccAg=,iv:4IFqGSAQvi1BkXF89bVP/iUVaN4nnF/9U1PBeDdFj34=,tag:n2Vxs7hu+e41ir3wlDaipA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
