postgres:
    connStr: ENC[AES256_GCM,data:oR58kRaWEyTRY+47lzi/S67lc4vDHn1NYC76hpNI0x86P4kjnFAS+pwAWBFu4BLT49rReXihwJwREvf+obH9HmqpUeGTTpe46bnRN2aQvV8BQu2B4XkPQMcE4EUOBmRGYqcq8dXsvcuAEjCkjumAYuxMRG//p87a4/wUmPWfhzEEXm4s6QdyHbbGgMiJqYNme2N9eukiVjlP/MAmoRiBeHdwC16DBHRi6spp,iv:TCL6xyuno+XcxzriWyRDLVLY7qbCafgB9+pioDQo2js=,tag:oV/V1Y67XvJpmGyRbI0okA==,type:str]
sops:
    age:
        - recipient: age12g7vcvqa7t5zm98ez0w66ecx040wqu2kw552cgrxqg0ry2mw299q64sxgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISzY3QSthVUQ2NXRON083
            YUc0Z21ORW1JRjNjZW9vZ1pCelJjZmNlQ3d3CnBwVkxTdkhEQUJNdjF2SHZIRmsy
            SHExMVkxOC9KS3RtdC84cmp5R1JwdDgKLS0tIHU4Q1RTVmFHZHRsOUR2WmdGeTg2
            bjgyRmNzc2NGSE4xUlZMeWRoNEhlUFEK5bJyaCaGFoALgkft+ry5VGjIB36uFnr4
            Gylsu6Dg0n0UIn6j/9gd3w/40r95N7zZyAUGmvjlNMvCrjGhp7ayCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:08:22Z"
    mac: ENC[AES256_GCM,data:4pFCvqNPhU2nJLX3LDbU9yGA2busM03lHQAK5MJBMsMCJIXtCaKhrg/xB7wyq0MWcfMR6CWp2Xy6P5v+bCijEylN/IitiCYdgVRmwNY/ywHu3c91J/QBKgkoITYLZ5AZBkwFkme7y/HJS9gT1db8JunyJcwecZl7MEe3RdxLUF0=,iv:09dDJWyU9BknHXQ4LgptCERZrlCb+siWZ69twPG2B3c=,tag:cTWV+WotirlxV51KP7QDCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
