// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/lbrefresher/leaderboard_refresher.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/lbrefresher/leaderboard_refresher.go -destination=internal/domain/lbrefresher/leaderboard_refresher_mock.go -package=lbrefresher
//

// Package lbrefresher is a generated GoMock package.
package lbrefresher

import (
	context "context"
	reflect "reflect"
	time "time"

	player "github.com/Mikhalevich/tg-penalty-game-bot/internal/domain/model/player"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// InsertHistoryScoreLeaderboard mocks base method.
func (m *MockRepository) InsertHistoryScoreLeaderboard(ctx context.Context, positions HistoryPositions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHistoryScoreLeaderboard", ctx, positions)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHistoryScoreLeaderboard indicates an expected call of InsertHistoryScoreLeaderboard.
func (mr *MockRepositoryMockRecorder) InsertHistoryScoreLeaderboard(ctx, positions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHistoryScoreLeaderboard", reflect.TypeOf((*MockRepository)(nil).InsertHistoryScoreLeaderboard), ctx, positions)
}

// PlayerScorePositionsFrom mocks base method.
func (m *MockRepository) PlayerScorePositionsFrom(ctx context.Context, positionFrom, limit int) ([]player.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerScorePositionsFrom", ctx, positionFrom, limit)
	ret0, _ := ret[0].([]player.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlayerScorePositionsFrom indicates an expected call of PlayerScorePositionsFrom.
func (mr *MockRepositoryMockRecorder) PlayerScorePositionsFrom(ctx, positionFrom, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerScorePositionsFrom", reflect.TypeOf((*MockRepository)(nil).PlayerScorePositionsFrom), ctx, positionFrom, limit)
}

// RefreshScoreLeaderboard mocks base method.
func (m *MockRepository) RefreshScoreLeaderboard(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshScoreLeaderboard", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshScoreLeaderboard indicates an expected call of RefreshScoreLeaderboard.
func (mr *MockRepositoryMockRecorder) RefreshScoreLeaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshScoreLeaderboard", reflect.TypeOf((*MockRepository)(nil).RefreshScoreLeaderboard), ctx)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockTransactor) Transaction(ctx context.Context, trxFn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, trxFn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockTransactorMockRecorder) Transaction(ctx, trxFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTransactor)(nil).Transaction), ctx, trxFn)
}

// MockSettingsProvider is a mock of SettingsProvider interface.
type MockSettingsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsProviderMockRecorder
	isgomock struct{}
}

// MockSettingsProviderMockRecorder is the mock recorder for MockSettingsProvider.
type MockSettingsProviderMockRecorder struct {
	mock *MockSettingsProvider
}

// NewMockSettingsProvider creates a new mock instance.
func NewMockSettingsProvider(ctrl *gomock.Controller) *MockSettingsProvider {
	mock := &MockSettingsProvider{ctrl: ctrl}
	mock.recorder = &MockSettingsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsProvider) EXPECT() *MockSettingsProviderMockRecorder {
	return m.recorder
}

// GetLeaderboardMonth mocks base method.
func (m *MockSettingsProvider) GetLeaderboardMonth(ctx context.Context) (time.Month, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboardMonth", ctx)
	ret0, _ := ret[0].(time.Month)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboardMonth indicates an expected call of GetLeaderboardMonth.
func (mr *MockSettingsProviderMockRecorder) GetLeaderboardMonth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboardMonth", reflect.TypeOf((*MockSettingsProvider)(nil).GetLeaderboardMonth), ctx)
}

// SetLeaderboardMonth mocks base method.
func (m *MockSettingsProvider) SetLeaderboardMonth(ctx context.Context, month time.Month) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLeaderboardMonth", ctx, month)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLeaderboardMonth indicates an expected call of SetLeaderboardMonth.
func (mr *MockSettingsProviderMockRecorder) SetLeaderboardMonth(ctx, month any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLeaderboardMonth", reflect.TypeOf((*MockSettingsProvider)(nil).SetLeaderboardMonth), ctx, month)
}

// MockTimeProvider is a mock of TimeProvider interface.
type MockTimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTimeProviderMockRecorder
	isgomock struct{}
}

// MockTimeProviderMockRecorder is the mock recorder for MockTimeProvider.
type MockTimeProviderMockRecorder struct {
	mock *MockTimeProvider
}

// NewMockTimeProvider creates a new mock instance.
func NewMockTimeProvider(ctrl *gomock.Controller) *MockTimeProvider {
	mock := &MockTimeProvider{ctrl: ctrl}
	mock.recorder = &MockTimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeProvider) EXPECT() *MockTimeProviderMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimeProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeProvider)(nil).Now))
}
